"""
Extended data models for storage layer.

These models represent the database schema for situations, documents,
analyses, alerts, and sources.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SituationStatus(str, Enum):
    """Status of a monitoring situation."""
    ACTIVE = "active"
    PAUSED = "paused"
    ARCHIVED = "archived"
    ERROR = "error"


class DocumentStatus(str, Enum):
    """Status of a document."""
    NEW = "new"
    FETCHING = "fetching"
    ANALYZED = "analyzed"
    FAILED = "failed"
    ARCHIVED = "archived"


class SourceCredibility(str, Enum):
    """Credibility level for sources."""
    HIGH = "high"      # Government, academic, official
    MEDIUM = "medium"  # Established media, reputable blogs
    LOW = "low"        # Unknown blogs, social media, forums


class AlertType(str, Enum):
    """Types of alerts that can be generated."""
    ENTITY_MENTION = "entity_mention"
    SENTIMENT_SHIFT = "sentiment_shift"
    VOLUME_SPIKE = "volume_spike"
    KEYWORD_MATCH = "keyword_match"
    ANOMALY_DETECTED = "anomaly_detected"
    SYSTEM = "system"


class SeverityLevel(str, Enum):
    """Severity levels for alerts."""
    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Situation(BaseModel):
    """
    A monitoring situation representing a topic/query being tracked.
    """
    id: str = Field(..., description="Unique situation ID (UUID)")
    query: str = Field(..., description="Original user query")
    parsed_entities: List[str] = Field(default_factory=list, description="Extracted entities")
    keywords: List[str] = Field(default_factory=list, description="Keywords for matching")
    description: Optional[str] = Field(None, description="Human-readable description")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    status: SituationStatus = Field(default=SituationStatus.ACTIVE)
    config: Dict[str, Any] = Field(default_factory=dict, description="Situation-specific settings")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class Document(BaseModel):
    """
    A document fetched from a source.
    """
    id: str = Field(..., description="Unique document ID (UUID)")
    situation_id: str = Field(..., description="Parent situation ID")
    source_url: str = Field(..., description="URL where document was found")
    content_hash: str = Field(..., description="SHA-256 hash for deduplication")
    title: Optional[str] = Field(None, description="Document title")
    text: str = Field(..., description="Full document text")
    summary: Optional[str] = Field(None, description="Auto-generated summary")
    published_at: Optional[datetime] = Field(None, description="Original publication date")
    fetched_at: datetime = Field(default_factory=datetime.utcnow)
    status: DocumentStatus = Field(default=DocumentStatus.NEW)
    language: Optional[str] = Field(None, description="Detected language code")
    word_count: int = Field(default=0)
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Source-specific metadata")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class Analysis(BaseModel):
    """
    NLP analysis results for a document.
    """
    id: str = Field(..., description="Unique analysis ID (UUID)")
    document_id: str = Field(..., description="Parent document ID")
    situation_id: str = Field(..., description="Parent situation ID")
    sentiment_score: float = Field(..., ge=-1.0, le=1.0, description="-1 negative to +1 positive")
    sentiment_label: str = Field(..., description="positive/negative/neutral/mixed")
    summary: str = Field(..., description="Generated summary")
    key_phrases: List[str] = Field(default_factory=list, description="Important phrases")
    entities: List[Dict[str, Any]] = Field(default_factory=list, description="Named entities")
    keywords: List[str] = Field(default_factory=list, description="Extracted keywords")
    topics: List[str] = Field(default_factory=list, description="Detected topics")
    readability_score: Optional[float] = Field(None, description="Flesch reading ease or similar")
    analyzed_at: datetime = Field(default_factory=datetime.utcnow)
    model_version: str = Field(default="unknown", description="NLP model used")
    processing_time_ms: Optional[int] = Field(None, description="Analysis duration")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class AlertRecord(BaseModel):
    """
    An alert generated by the monitoring system.
    """
    id: str = Field(..., description="Unique alert ID (UUID)")
    situation_id: str = Field(..., description="Parent situation ID")
    document_id: Optional[str] = Field(None, description="Related document ID")
    analysis_id: Optional[str] = Field(None, description="Related analysis ID")
    alert_type: AlertType = Field(..., description="Type of alert")
    severity: SeverityLevel = Field(..., description="Alert severity")
    message: str = Field(..., description="Human-readable alert message")
    details: Dict[str, Any] = Field(default_factory=dict, description="Structured alert data")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    acknowledged: bool = Field(default=False)
    acknowledged_at: Optional[datetime] = Field(None)
    acknowledged_by: Optional[str] = Field(None)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class MonitoredSource(BaseModel):
    """
    A source being monitored for a situation.
    """
    id: str = Field(..., description="Unique source ID (UUID)")
    situation_id: str = Field(..., description="Parent situation ID")
    url: str = Field(..., description="Source URL or identifier")
    source_type: str = Field(..., description="rss, api, file, web, etc.")
    credibility_score: float = Field(default=0.5, ge=0.0, le=1.0)
    credibility_label: SourceCredibility = Field(default=SourceCredibility.MEDIUM)
    last_fetched: Optional[datetime] = Field(None)
    fetch_count: int = Field(default=0)
    document_count: int = Field(default=0)
    status: str = Field(default="active")  # active, paused, error, disabled
    error_count: int = Field(default=0)
    last_error: Optional[str] = Field(None)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class TimeSeriesPoint(BaseModel):
    """A single point in a time series."""
    timestamp: datetime
    value: float
    count: int = Field(default=1)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TrendAnalysis(BaseModel):
    """Trend analysis results for a situation."""
    situation_id: str
    metric: str  # sentiment, volume, mentions, etc.
    period_start: datetime
    period_end: datetime
    data_points: List[TimeSeriesPoint]
    trend_direction: str  # increasing, decreasing, stable
    trend_strength: float  # 0.0 to 1.0
    anomalies: List[Dict[str, Any]] = Field(default_factory=list)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class SearchResult(BaseModel):
    """Result from a full-text or semantic search."""
    document_id: str
    title: Optional[str]
    snippet: str
    score: float
    rank: int
    highlights: List[str] = Field(default_factory=list)


# ============================================================================
# Health Check Functions
# ============================================================================

def check_storage_health() -> bool:
    """
    Check if storage is accessible and functioning.
    
    Returns:
        True if storage is healthy, False otherwise.
    """
    try:
        from situation_monitor.config.settings import get_settings
        settings = get_settings()
        
        # Check if data directory exists and is writable
        if not settings.data_dir.exists():
            return False
        
        # Try to write a test file
        test_file = settings.data_dir / ".health_check"
        try:
            test_file.touch()
            test_file.unlink()
        except (OSError, PermissionError):
            return False
        
        return True
    except Exception:
        return False
